// <auto-generated by="the Blazor I18n Text compiler" />
namespace Lib4PackRef6.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash.Hash => "yu8qczfacr";

        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"This Blazor component is defined in the Lib4PackRef6 package."</summary>
        public string Message;
    }
}
